# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: roster.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'roster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0croster.proto\"\\\n\x04\x43lub\x12\x0e\n\x06\x43lubID\x18\x01 \x01(\t\x12\x10\n\x08\x43lubName\x18\x02 \x01(\t\x12\x13\n\x0b\x46oundedYear\x18\x03 \x01(\x05\x12\x0c\n\x04\x43ity\x18\x04 \x01(\t\x12\x0f\n\x07\x43ountry\x18\x05 \x01(\t\" \n\x08\x43lubList\x12\x14\n\x05\x63lubs\x18\x01 \x03(\x0b\x32\x05.Club\"\xc3\x01\n\x06Player\x12\x10\n\x08playerid\x18\x01 \x01(\t\x12\x0e\n\x06jersey\x18\x02 \x01(\x05\x12\r\n\x05\x66name\x18\x03 \x01(\t\x12\r\n\x05sname\x18\x04 \x01(\t\x12\x10\n\x08position\x18\x05 \x01(\t\x12\x10\n\x08\x62irthday\x18\x06 \x01(\t\x12\x0e\n\x06weight\x18\x07 \x01(\x05\x12\x0e\n\x06height\x18\x08 \x01(\x05\x12\x11\n\tbirthcity\x18\t \x01(\t\x12\x12\n\nbirthstate\x18\n \x01(\t\x12\x0e\n\x06\x43lubID\x18\x0b \x01(\t\"&\n\nPlayerList\x12\x18\n\x07players\x18\x01 \x03(\x0b\x32\x07.Player\"\x11\n\x0fGetClubsRequest\")\n\x17GetPlayersByClubRequest\x12\x0e\n\x06\x43lubID\x18\x01 \x01(\t\"\xd0\x01\n\x13UpdatePlayerRequest\x12\x10\n\x08playerid\x18\x01 \x01(\t\x12\x0e\n\x06jersey\x18\x02 \x01(\x05\x12\r\n\x05\x66name\x18\x03 \x01(\t\x12\r\n\x05sname\x18\x04 \x01(\t\x12\x10\n\x08position\x18\x05 \x01(\t\x12\x10\n\x08\x62irthday\x18\x06 \x01(\t\x12\x0e\n\x06weight\x18\x07 \x01(\x05\x12\x0e\n\x06height\x18\x08 \x01(\x05\x12\x11\n\tbirthcity\x18\t \x01(\t\x12\x12\n\nbirthstate\x18\n \x01(\t\x12\x0e\n\x06\x43lubID\x18\x0b \x01(\t\"\'\n\x14UpdatePlayerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb6\x01\n\rRosterService\x12)\n\x08GetClubs\x12\x10.GetClubsRequest\x1a\t.ClubList\"\x00\x12;\n\x10GetPlayersByClub\x12\x18.GetPlayersByClubRequest\x1a\x0b.PlayerList\"\x00\x12=\n\x0cUpdatePlayer\x12\x14.UpdatePlayerRequest\x1a\x15.UpdatePlayerResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'roster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLUB']._serialized_start=16
  _globals['_CLUB']._serialized_end=108
  _globals['_CLUBLIST']._serialized_start=110
  _globals['_CLUBLIST']._serialized_end=142
  _globals['_PLAYER']._serialized_start=145
  _globals['_PLAYER']._serialized_end=340
  _globals['_PLAYERLIST']._serialized_start=342
  _globals['_PLAYERLIST']._serialized_end=380
  _globals['_GETCLUBSREQUEST']._serialized_start=382
  _globals['_GETCLUBSREQUEST']._serialized_end=399
  _globals['_GETPLAYERSBYCLUBREQUEST']._serialized_start=401
  _globals['_GETPLAYERSBYCLUBREQUEST']._serialized_end=442
  _globals['_UPDATEPLAYERREQUEST']._serialized_start=445
  _globals['_UPDATEPLAYERREQUEST']._serialized_end=653
  _globals['_UPDATEPLAYERRESPONSE']._serialized_start=655
  _globals['_UPDATEPLAYERRESPONSE']._serialized_end=694
  _globals['_ROSTERSERVICE']._serialized_start=697
  _globals['_ROSTERSERVICE']._serialized_end=879
# @@protoc_insertion_point(module_scope)
