# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import roster_pb2 as roster__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in roster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RosterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetClubs = channel.unary_unary(
                '/RosterService/GetClubs',
                request_serializer=roster__pb2.GetClubsRequest.SerializeToString,
                response_deserializer=roster__pb2.ClubList.FromString,
                _registered_method=True)
        self.GetPlayersByClub = channel.unary_unary(
                '/RosterService/GetPlayersByClub',
                request_serializer=roster__pb2.GetPlayersByClubRequest.SerializeToString,
                response_deserializer=roster__pb2.PlayerList.FromString,
                _registered_method=True)
        self.UpdatePlayer = channel.unary_unary(
                '/RosterService/UpdatePlayer',
                request_serializer=roster__pb2.UpdatePlayerRequest.SerializeToString,
                response_deserializer=roster__pb2.UpdatePlayerResponse.FromString,
                _registered_method=True)


class RosterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetClubs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayersByClub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RosterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetClubs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClubs,
                    request_deserializer=roster__pb2.GetClubsRequest.FromString,
                    response_serializer=roster__pb2.ClubList.SerializeToString,
            ),
            'GetPlayersByClub': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayersByClub,
                    request_deserializer=roster__pb2.GetPlayersByClubRequest.FromString,
                    response_serializer=roster__pb2.PlayerList.SerializeToString,
            ),
            'UpdatePlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlayer,
                    request_deserializer=roster__pb2.UpdatePlayerRequest.FromString,
                    response_serializer=roster__pb2.UpdatePlayerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RosterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RosterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RosterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetClubs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RosterService/GetClubs',
            roster__pb2.GetClubsRequest.SerializeToString,
            roster__pb2.ClubList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlayersByClub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RosterService/GetPlayersByClub',
            roster__pb2.GetPlayersByClubRequest.SerializeToString,
            roster__pb2.PlayerList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RosterService/UpdatePlayer',
            roster__pb2.UpdatePlayerRequest.SerializeToString,
            roster__pb2.UpdatePlayerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
