# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: roster.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'roster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0croster.proto\"\xa0\x01\n\x0cPlayerFilter\x12\x10\n\x08position\x18\x01 \x01(\t\x12\x17\n\x0f\x62irth_year_from\x18\x02 \x01(\x05\x12\x15\n\rbirth_year_to\x18\x03 \x01(\x05\x12\x13\n\x0bweight_from\x18\x04 \x01(\x05\x12\x11\n\tweight_to\x18\x05 \x01(\x05\x12\x13\n\x0bheight_from\x18\x06 \x01(\x05\x12\x11\n\theight_to\x18\x07 \x01(\x05\"\xb3\x01\n\x06Player\x12\x10\n\x08playerid\x18\x01 \x01(\t\x12\x0e\n\x06jersey\x18\x02 \x01(\x05\x12\r\n\x05\x66name\x18\x03 \x01(\t\x12\r\n\x05sname\x18\x04 \x01(\t\x12\x10\n\x08position\x18\x05 \x01(\t\x12\x10\n\x08\x62irthday\x18\x06 \x01(\t\x12\x0e\n\x06weight\x18\x07 \x01(\x05\x12\x0e\n\x06height\x18\x08 \x01(\x05\x12\x11\n\tbirthcity\x18\t \x01(\t\x12\x12\n\nbirthstate\x18\n \x01(\t\"&\n\nPlayerList\x12\x18\n\x07players\x18\x01 \x03(\x0b\x32\x07.Player2;\n\rRosterService\x12*\n\nGetPlayers\x12\r.PlayerFilter\x1a\x0b.PlayerList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'roster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYERFILTER']._serialized_start=17
  _globals['_PLAYERFILTER']._serialized_end=177
  _globals['_PLAYER']._serialized_start=180
  _globals['_PLAYER']._serialized_end=359
  _globals['_PLAYERLIST']._serialized_start=361
  _globals['_PLAYERLIST']._serialized_end=399
  _globals['_ROSTERSERVICE']._serialized_start=401
  _globals['_ROSTERSERVICE']._serialized_end=460
# @@protoc_insertion_point(module_scope)
